using System.Collections.Generic;

namespace ClydeMenu.Engine;

// autogenerated
internal class Storage
{
    public static bool Godmode
    {
        get;
        internal set;
    }
    public static string CmdBarInput
    {
        get;
        internal set;
    } = "";
    public static bool CmdBarJustShown
    {
        get;
        internal set;
    }
    public static int CmdBarInputID
    {
        get;
        internal set;
    }
    public static List<string> CmdBarHistory
    {
        get;
        internal set;
    } = [];
    public static int CmdBarHistoryIndex
    {
        get;
        internal set;
    }
    public static bool AntiKick
    {
        get;
        internal set;
    } = false;
}