using System.Collections.Generic;
using System.Configuration;

namespace ClydeMenu.Engine;

// autogenerated
internal class Storage
{
    public static bool MOD_Godmode
    {
        get;
        internal set;
    }
    public static string CmdBarInput
    {
        get;
        internal set;
    } = "";
    public static bool CmdBarJustShown
    {
        get;
        internal set;
    }
    public static int CmdBarInputID
    {
        get;
        internal set;
    }
    public static List<string> CmdBarHistory
    {
        get;
        internal set;
    } = [];
    public static int CmdBarHistoryIndex
    {
        get;
        internal set;
    }
    public static bool MOD_AntiKickMsg
    {
        get;
        internal set;
    } = false;
    public static bool MOD_RandomizeName
    {
        get;
        internal set;
    }
    public static class Network
    {
        public static bool CanSendPackets
        {
            get;
            internal set;
        } = false;
    }
}
